### ISSUE TITLE
Error when the compund name is int/float

### ISSUE THREAD

**Issue by filipsPL** [filipsPL/annapurna#3]
```
[ Info ] Clustering with AD
[ Info ] Processing 2762681 ...
[ Info ] AD Clustering...
Traceback (most recent call last):
  File "/home/fstefaniak/git/github/annapurna/annapurna.py", line 1648, in <module>
    groupByName = args.groupByName, E_weight = args.EnergyWeight)
  File "/home/fstefaniak/git/github/annapurna/annapurna.py", line 1326, in scoreLoop
    outputScore = cluster(outputScore, sdffile, ClusteringMethod, ClusteringFraction, ClusteringCutoff, outputFilename, modelName)
  File "/home/fstefaniak/git/github/annapurna/annapurna.py", line 1169, in cluster
    mol.data['Pose_Number'] = selectedMoleculeGlobal['compoundId']
AttributeError: 'float' object has no attribute 'data'
```

**Comment by filipsPL** [comment]
Fix: change column type of `compound` to be string. (pandas)

**Comment by filipsPL** [comment]
Fixed in float-in-names
